# .travis.yml for R projects

os:
  - linux
  - osx

language: r
r:
  - oldrel
  - release

warnings_are_errors: true

sudo: required

r_packages:
  - covr

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'library(covr); codecov(type="all")' Using Wercker CI ; fi

# install sglOptim
r_github_packages:
 - vincent-dk/sglOptim
