# .travis.yml for R projects

os:
  - linux
  - osx

language: r
r:
  - 3.2
  - release

warnings_are_errors: true

sudo: required

r_packages:
  - knitr

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'install.packages("covr"); library(covr); codecov(type="all", quite = FALSE)' Using Wercker CI ; fi

# install sglOptim
r_github_packages:
 - vincent-dk/sglOptim
